# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/YHOAUANN"

[social.params]
icon = "brand-github"
newTab: true

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/yhoaua"

[social.params]
icon = "brand-twitter"
newTab: true

[[social]]
identifier = "netease-music"
name = "NeteaseMusic"
url = "https://music.163.com/#/user/home?id=8493943724"

[social.params]
icon = "brand-netease-music"
newTab: true

[[social]]
identifier = "bilibili"
name = "Bilibili"
url = "https://space.bilibili.com/431471608"

[social.params]
icon = "brand-bilibili"
newTab: true

[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://www.instagram.com/yhoauann"

[social.params]
icon = "brand-instagram"
newTab: true

[[social]]
identifier = "youtube"
name = "Youtube"
url = "https://www.youtube.com/@yhoauann"

[social.params]
icon = "brand-youtube"
newTab: true

